# Generated by Django 4.0.1 on 2022-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Məhsulun adı')),
                ('mehsulun_kodu', models.TextField(max_length=20, verbose_name='Məhsulun kodu')),
                ('alt_dolap_eni', models.TextField(max_length=10, verbose_name='Alt şkafın eni')),
                ('alt_dolap_hundurluyu', models.TextField(max_length=10, verbose_name='Alt şkafın hündürlüyü')),
                ('alt_dolap_derinliyi', models.TextField(max_length=10, verbose_name='Alt şkafın dərinliyi')),
                ('ust_dolap_eni', models.TextField(max_length=10, verbose_name='Üst şkafın eni')),
                ('ust_dolap_hundurluyu', models.TextField(max_length=10, verbose_name='Üst şkafın hündürlüyü')),
                ('ust_dolap_derinliyi', models.TextField(max_length=10, verbose_name='Üst şkafın dərinliyi')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Məhsulun şəkli')),
                ('available', models.BooleanField(default=False, verbose_name='Yayımlansın?')),
            ],
        ),
    ]
