# Generated by Django 4.0.1 on 2022-01-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alt_dolap_derinliyi',
            field=models.CharField(max_length=10, verbose_name='Alt şkafın dərinliyi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt_dolap_eni',
            field=models.CharField(max_length=10, verbose_name='Alt şkafın eni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt_dolap_hundurluyu',
            field=models.CharField(max_length=10, verbose_name='Alt şkafın hündürlüyü'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mehsulun_kodu',
            field=models.CharField(max_length=20, verbose_name='Məhsulun kodu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ust_dolap_derinliyi',
            field=models.CharField(max_length=10, verbose_name='Üst şkafın dərinliyi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ust_dolap_eni',
            field=models.CharField(max_length=10, verbose_name='Üst şkafın eni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ust_dolap_hundurluyu',
            field=models.CharField(max_length=10, verbose_name='Üst şkafın hündürlüyü'),
        ),
    ]
