# Generated by Django 4.0.1 on 2022-01-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Yayımlanır'),
        ),
    ]
