# Generated by Django 4.0.1 on 2022-01-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220117_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_of_month',
            field=models.BooleanField(default=False, verbose_name='Ayın məhsulu'),
        ),
    ]
